# Generated by Django 3.2.5 on 2022-02-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('img', models.ImageField(upload_to='static/img', verbose_name='图片')),
                ('time', models.DateField(max_length=20, verbose_name='时间')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='文案')),
                ('time', models.DateTimeField(max_length=50, verbose_name='时间')),
                ('imgs', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片')),
                ('public', models.IntegerField(default=0, verbose_name='是否公开')),
            ],
            options={
                'db_table': 'share',
            },
        ),
        migrations.CreateModel(
            name='ShareAlbum',
            fields=[
                ('sa_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('sa_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='相册名')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='文案')),
                ('time', models.DateField(max_length=20, verbose_name='时间')),
                ('imgs', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片')),
            ],
            options={
                'db_table': 'shareAlbum',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.share')),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'user_share',
                'unique_together': {('u_id', 's_id')},
            },
        ),
        migrations.CreateModel(
            name='User_SA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_id', models.ForeignKey(db_column='sa_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.sharealbum')),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'user_sa',
                'unique_together': {('u_id', 'sa_id')},
            },
        ),
        migrations.CreateModel(
            name='User_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'user_img',
                'unique_together': {('u_id', 'img_id')},
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_id', to='Photoalbum.user')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_id', to='Photoalbum.user')),
            ],
            options={
                'db_table': 'friends',
                'unique_together': {('u_id', 'f_id')},
            },
        ),
    ]
