# Generated by Django 3.2.5 on 2022-01-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('time', models.CharField(max_length=20, verbose_name='时间')),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'user_img',
            },
        ),
    ]
