# Generated by Django 3.2.5 on 2022-02-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='sharealbum',
            name='imgs',
        ),
        migrations.CreateModel(
            name='SA_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
                ('sa_id', models.ForeignKey(db_column='sa_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.sharealbum')),
            ],
            options={
                'db_table': 'sa_picture',
            },
        ),
        migrations.CreateModel(
            name='S_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
                ('s_id', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.share')),
            ],
            options={
                'db_table': 's_picture',
            },
        ),
    ]
