# Generated by Django 3.2.5 on 2022-02-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0003_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facelist_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='user_id')),
                ('user_info', models.CharField(max_length=50, verbose_name='user_info')),
                ('group_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'facelist_info',
                'unique_together': {('group_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='SA_upload',
            fields=[
                ('sau_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('time', models.DateField(max_length=20, verbose_name='时间')),
                ('sa_id', models.ForeignKey(db_column='sa_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.sharealbum')),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'sa_upload',
            },
        ),
        migrations.CreateModel(
            name='SAU_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
                ('sau_id', models.ForeignKey(db_column='sau_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.sa_upload')),
            ],
            options={
                'db_table': 'sau_picture',
            },
        ),
        migrations.DeleteModel(
            name='SA_picture',
        ),
    ]
