# Generated by Django 3.2.5 on 2022-02-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0005_group_user_user_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_user',
            name='user_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user_info'),
        ),
        migrations.AddField(
            model_name='user_face',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='u_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user'),
        ),
        migrations.AlterUniqueTogether(
            name='user_face',
            unique_together={('group_id', 'user_id', 'face_id')},
        ),
        migrations.DeleteModel(
            name='Facelist_info',
        ),
    ]
