# Generated by Django 3.2.5 on 2022-02-14 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0006_auto_20220214_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=50, verbose_name='person_id')),
                ('person_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='person_info')),
                ('group_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'group_person',
                'unique_together': {('group_id', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='Person_face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=50, verbose_name='person_id')),
                ('face_id', models.ForeignKey(db_column='face_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.face')),
                ('group_id', models.ForeignKey(blank=True, db_column='u_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.user')),
            ],
            options={
                'db_table': 'person_face',
                'unique_together': {('group_id', 'person_id', 'face_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='user_face',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='user_face',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='user_face',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='Group_user',
        ),
        migrations.DeleteModel(
            name='User_face',
        ),
    ]
