# Generated by Django 3.2.5 on 2022-02-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0008_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='c_id')),
                ('classname', models.CharField(max_length=50, verbose_name='classname')),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Class_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.class')),
                ('img_id', models.ForeignKey(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to='Photoalbum.img')),
            ],
            options={
                'db_table': 'class_img',
                'unique_together': {('c_id', 'img_id')},
            },
        ),
    ]
