# Generated by Django 3.2.5 on 2022-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photoalbum', '0009_class_class_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharealbum',
            name='text',
        ),
        migrations.AddField(
            model_name='sa_upload',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文案'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像'),
        ),
    ]
